import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "../theme/themeProvider";
import Header from "@/components/Header/Header";
import Box from "@mui/material/Box";
import { CartProvider } from "@/providers/CartProvider";
import SearchProvider from "@/providers/SearchProvider";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense>
          <ThemeProvider>
            <CartProvider>
              <SearchProvider>
                <Box sx={{bgcolor: 'background.default'}}>
                  <Header />
                  <Box pt={8} minHeight="calc(100vh - 64px)">
                    {children}
                  </Box>
                </Box>
              </SearchProvider>
            </CartProvider>
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
